/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

// Import Routes

import { Route as rootRoute } from './routes/__root'
import { Route as QuizzesImport } from './routes/quizzes'
import { Route as QuizBuilderImport } from './routes/quiz-builder'
import { Route as IndexImport } from './routes/index'
import { Route as QuizResponseQuizIdImport } from './routes/quiz-response.$quizId'
import { Route as QuizBuilderQuizIdImport } from './routes/quiz-builder.$quizId'

// Create/Update Routes

const QuizzesRoute = QuizzesImport.update({
  id: '/quizzes',
  path: '/quizzes',
  getParentRoute: () => rootRoute,
} as any)

const QuizBuilderRoute = QuizBuilderImport.update({
  id: '/quiz-builder',
  path: '/quiz-builder',
  getParentRoute: () => rootRoute,
} as any)

const IndexRoute = IndexImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRoute,
} as any)

const QuizResponseQuizIdRoute = QuizResponseQuizIdImport.update({
  id: '/quiz-response/$quizId',
  path: '/quiz-response/$quizId',
  getParentRoute: () => rootRoute,
} as any)

const QuizBuilderQuizIdRoute = QuizBuilderQuizIdImport.update({
  id: '/$quizId',
  path: '/$quizId',
  getParentRoute: () => QuizBuilderRoute,
} as any)

// Populate the FileRoutesByPath interface

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexImport
      parentRoute: typeof rootRoute
    }
    '/quiz-builder': {
      id: '/quiz-builder'
      path: '/quiz-builder'
      fullPath: '/quiz-builder'
      preLoaderRoute: typeof QuizBuilderImport
      parentRoute: typeof rootRoute
    }
    '/quizzes': {
      id: '/quizzes'
      path: '/quizzes'
      fullPath: '/quizzes'
      preLoaderRoute: typeof QuizzesImport
      parentRoute: typeof rootRoute
    }
    '/quiz-builder/$quizId': {
      id: '/quiz-builder/$quizId'
      path: '/$quizId'
      fullPath: '/quiz-builder/$quizId'
      preLoaderRoute: typeof QuizBuilderQuizIdImport
      parentRoute: typeof QuizBuilderImport
    }
    '/quiz-response/$quizId': {
      id: '/quiz-response/$quizId'
      path: '/quiz-response/$quizId'
      fullPath: '/quiz-response/$quizId'
      preLoaderRoute: typeof QuizResponseQuizIdImport
      parentRoute: typeof rootRoute
    }
  }
}

// Create and export the route tree

interface QuizBuilderRouteChildren {
  QuizBuilderQuizIdRoute: typeof QuizBuilderQuizIdRoute
}

const QuizBuilderRouteChildren: QuizBuilderRouteChildren = {
  QuizBuilderQuizIdRoute: QuizBuilderQuizIdRoute,
}

const QuizBuilderRouteWithChildren = QuizBuilderRoute._addFileChildren(
  QuizBuilderRouteChildren,
)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/quiz-builder': typeof QuizBuilderRouteWithChildren
  '/quizzes': typeof QuizzesRoute
  '/quiz-builder/$quizId': typeof QuizBuilderQuizIdRoute
  '/quiz-response/$quizId': typeof QuizResponseQuizIdRoute
}

export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/quiz-builder': typeof QuizBuilderRouteWithChildren
  '/quizzes': typeof QuizzesRoute
  '/quiz-builder/$quizId': typeof QuizBuilderQuizIdRoute
  '/quiz-response/$quizId': typeof QuizResponseQuizIdRoute
}

export interface FileRoutesById {
  __root__: typeof rootRoute
  '/': typeof IndexRoute
  '/quiz-builder': typeof QuizBuilderRouteWithChildren
  '/quizzes': typeof QuizzesRoute
  '/quiz-builder/$quizId': typeof QuizBuilderQuizIdRoute
  '/quiz-response/$quizId': typeof QuizResponseQuizIdRoute
}

export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/quiz-builder'
    | '/quizzes'
    | '/quiz-builder/$quizId'
    | '/quiz-response/$quizId'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/quiz-builder'
    | '/quizzes'
    | '/quiz-builder/$quizId'
    | '/quiz-response/$quizId'
  id:
    | '__root__'
    | '/'
    | '/quiz-builder'
    | '/quizzes'
    | '/quiz-builder/$quizId'
    | '/quiz-response/$quizId'
  fileRoutesById: FileRoutesById
}

export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  QuizBuilderRoute: typeof QuizBuilderRouteWithChildren
  QuizzesRoute: typeof QuizzesRoute
  QuizResponseQuizIdRoute: typeof QuizResponseQuizIdRoute
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  QuizBuilderRoute: QuizBuilderRouteWithChildren,
  QuizzesRoute: QuizzesRoute,
  QuizResponseQuizIdRoute: QuizResponseQuizIdRoute,
}

export const routeTree = rootRoute
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

/* ROUTE_MANIFEST_START
{
  "routes": {
    "__root__": {
      "filePath": "__root.tsx",
      "children": [
        "/",
        "/quiz-builder",
        "/quizzes",
        "/quiz-response/$quizId"
      ]
    },
    "/": {
      "filePath": "index.tsx"
    },
    "/quiz-builder": {
      "filePath": "quiz-builder.tsx",
      "children": [
        "/quiz-builder/$quizId"
      ]
    },
    "/quizzes": {
      "filePath": "quizzes.tsx"
    },
    "/quiz-builder/$quizId": {
      "filePath": "quiz-builder.$quizId.tsx",
      "parent": "/quiz-builder"
    },
    "/quiz-response/$quizId": {
      "filePath": "quiz-response.$quizId.tsx"
    }
  }
}
ROUTE_MANIFEST_END */
