/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

// Import Routes

import { Route as rootRoute } from './routes/__root'
import { Route as QuizzesImport } from './routes/quizzes'
import { Route as QuizBuilderImport } from './routes/quiz-builder'
import { Route as IndexImport } from './routes/index'

// Create/Update Routes

const QuizzesRoute = QuizzesImport.update({
  id: '/quizzes',
  path: '/quizzes',
  getParentRoute: () => rootRoute,
} as any)

const QuizBuilderRoute = QuizBuilderImport.update({
  id: '/quiz-builder',
  path: '/quiz-builder',
  getParentRoute: () => rootRoute,
} as any)

const IndexRoute = IndexImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRoute,
} as any)

// Populate the FileRoutesByPath interface

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexImport
      parentRoute: typeof rootRoute
    }
    '/quiz-builder': {
      id: '/quiz-builder'
      path: '/quiz-builder'
      fullPath: '/quiz-builder'
      preLoaderRoute: typeof QuizBuilderImport
      parentRoute: typeof rootRoute
    }
    '/quizzes': {
      id: '/quizzes'
      path: '/quizzes'
      fullPath: '/quizzes'
      preLoaderRoute: typeof QuizzesImport
      parentRoute: typeof rootRoute
    }
  }
}

// Create and export the route tree

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/quiz-builder': typeof QuizBuilderRoute
  '/quizzes': typeof QuizzesRoute
}

export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/quiz-builder': typeof QuizBuilderRoute
  '/quizzes': typeof QuizzesRoute
}

export interface FileRoutesById {
  __root__: typeof rootRoute
  '/': typeof IndexRoute
  '/quiz-builder': typeof QuizBuilderRoute
  '/quizzes': typeof QuizzesRoute
}

export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths: '/' | '/quiz-builder' | '/quizzes'
  fileRoutesByTo: FileRoutesByTo
  to: '/' | '/quiz-builder' | '/quizzes'
  id: '__root__' | '/' | '/quiz-builder' | '/quizzes'
  fileRoutesById: FileRoutesById
}

export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  QuizBuilderRoute: typeof QuizBuilderRoute
  QuizzesRoute: typeof QuizzesRoute
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  QuizBuilderRoute: QuizBuilderRoute,
  QuizzesRoute: QuizzesRoute,
}

export const routeTree = rootRoute
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

/* ROUTE_MANIFEST_START
{
  "routes": {
    "__root__": {
      "filePath": "__root.tsx",
      "children": [
        "/",
        "/quiz-builder",
        "/quizzes"
      ]
    },
    "/": {
      "filePath": "index.tsx"
    },
    "/quiz-builder": {
      "filePath": "quiz-builder.tsx"
    },
    "/quizzes": {
      "filePath": "quizzes.tsx"
    }
  }
}
ROUTE_MANIFEST_END */
